name = "ouro-store"
main = "src/index.ts"
compatibility_date = "2025-03-01"
workers_dev = true

routes = [
  { pattern = "store.ouroskill.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "ouro-store-db"
database_id = "80b5c835-4541-449a-a99a-f85cdc174a78"

# [[r2_buckets]]
# binding = "SKILL_BUNDLES"
# bucket_name = "ouro-skill-bundles"
